framework:
    messenger:
        failure_transport: failed_queue

        transports:
             global_queue:
                 dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                 options:
                    table_name: 'global_queue'
             letter_processing_queue:
                 dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                 options:
                    table_name: 'letter_processing_queue'
             failed_queue:
                 dsn: '%env(MESSENGER_FAILED_TRANSPORT_DSN)%'
                 options:
                    table_name: 'failed_queue'
             sync: 'sync://'

        routing:
          App\LetterProcessing\Shared\Domain\ChildWasCreated: global_queue

        default_bus: default.bus
        buses:
            default.bus:

            command.bus:
                middleware:
                    - doctrine_transaction
                    - validation

            query.bus:

            event.bus:
                default_middleware: allow_no_handlers

when@test:
    framework:
        messenger:
            transports:
                # replace with your transport name here (e.g., my_transport: 'in-memory://')
                # For more Messenger testing tools, see https://github.com/zenstruck/messenger-test
                global_queue: 'in-memory://'
                letter_processing_queue: 'in-memory://'
                failed_queue: 'in-memory://'